## Numpy
### it is very powerful mathematical python library, it will be used a lot while making machine learning algorithms 

In [2]:
# importing numpy
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
# the shape attribute returns the dimensions of the array in the form of tuple, rows into columns
# because it is a linear array so its shape comes out to be (5,). in case of a 2d array with 5 rows and 1 column the shape would 
# be (5,1)
print(a.shape)
a1 = [1,2,3,4]
a2 = [4,5,6,8]
a3 = [a1,a2]
print(np.array(a3))
a4 = np.array(a3)
# now a4 is a 2d array hence its dimensions are 2X4(2 represents rows and 4 represents columns)
print(a4.shape)
b = np.array([[1,2],[3,4],[5,6]])
print(b)
print(b.shape)
print(b[0][1])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3 4]
 [4 5 6 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2


In [41]:
# creating array of zeroes, ones and custom arrays
c = np.zeros((4,4))
print(c)
print(type(c))
d = np.ones((3,3))
print(d)

# array of some constants 
# first argument takes rows and columns and second one takes the constant
e = np.full((3,2),6)
print(e)

# identity matrix(square matrix)
print(np.eye(4))

# random matrix, matrix of random integers
ran = np.random.random((3,2))
print(ran)
# to get multiple values from the matrix, : means for all
print(ran[:,1])
# to update entries in a matrix, 1: means starting from 1 upto last element or we could say 1:3 coz starting point is included
# and ending point is not included
ran[1:,1] = 22
print(ran)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6 6]
 [6 6]
 [6 6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.50958522 0.82788196]
 [0.56587257 0.18161643]
 [0.29327075 0.42072299]]
[0.82788196 0.18161643 0.42072299]
[[ 0.50958522  0.82788196]
 [ 0.56587257 22.        ]
 [ 0.29327075 22.        ]]


In [47]:
# datatypes

# by default the datatype is float but can be changed to integer
print(c.dtype)
z = np.zeros((3,3), dtype = np.int64)
print(z)
print(z.dtype)

float64
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [55]:
# mathematical operations 
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[5,6],[7,8]])
# operations are performed elementwise, add subtract multiply divide sqrt
print(np.add(x1,x2))
print(x1-x2)

# matrix multiplication and dot product
print(x1.dot(x2))
print(np.dot(x1,x2))

# multiplication of vectors(dot product), we get a scalar value
y1 = np.array([1,2,3])
y2 = np.array([1,2,3])
print(y1.dot(y2))

# sum of elements of an array
print(np.sum(y1))
print(sum(y2))
# it takes an optional parameter, axis = 0 means that it will give sum along the column, elements along the same row will be 
# summed up together, axis = 1 will give sum along the rows
print(np.sum(x1, axis = 0))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
14
6
6
[4 6]


In [59]:
# stacking of arrays, this will join two arrays or concatenate it 
y1 = y1**2
# the axis parameter specifies the index of the new axis in the dimensions of the result
# along axis = 1 the first array becomes the first column and the second array becomes the second column
print(np.stack((y1,y2), axis = 1))
print(np.stack((y1,y2), axis = 0))

[[       1        1]
 [   65536        2]
 [43046721        3]]
[[       1    65536 43046721]
 [       1        2        3]]


In [67]:
# reshaping the array
zer = np.zeros((4,4))
print(zer)
zer = zer.reshape((2,8))
print(zer)
# when you dont know how many rows or columns should be there then put -1 and it will figure out itself
zer = zer.reshape((8, -1))
print(zer)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


## Numpy Random Module
### it is a very powerful module when it comes to working with random distributions and numbers

In [82]:
# np.arange is used to create numeric sequences
w1 = np.arange(10)
print(w1)
w2 = np.arange(10) + 5 
print(w2)

# to shuffle the elements of the array in random order
np.random.shuffle(w2)
print(w2)

# to generate an array of random numbers, the parameter passed is the shape of the array
# returns value from standard normal distribution
w3 = np.random.rand(4,3)
print(w3)

# it will give us 3 numbers which are in the range of 5 and 10
w4 = np.random.randint(5,10,3)
print(w4)

# to randomly pick an element from an array
ele = np.random.choice([1,2,3,4,5,6])
print(ele)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[10 11  8 14  6  5 12  9 13  7]
[[0.81965067 0.72647703 0.77182528]
 [0.26916488 0.50126571 0.31294434]
 [0.16095071 0.83112833 0.389291  ]
 [0.46601064 0.10686235 0.9134528 ]]
[7 9 9]
2


In [122]:
# it uses a particular algorithm to generate pseudorandom numbers, so we use the concept of seed.
# we define seed to make the random numbers predictable and not so much random
np.random.seed(1)
w5 = np.random.randint(1,10,3)
print(w5)

[6 9 6]


## More numpy functions

In [3]:
w6 = np.array([[1,2,3,4],[8,9,6,0]])
# gives the minimum value in the whole array
print(np.min(w6))
# to get minimum value accross axis = 0, 1, to specify the direction
print(np.max(w6, axis = 1))

# to average all the elements, to find mean, simillarly here too the axis can be specified
print(np.mean(w6))

# to compute median, data be in ascending order
w7 = np.array([4,5,6,1,2])
print(np.median(w7))

0
[4 9]
4.125
4.0


In [11]:
# weights
w8 = np.array([1,2,3,4])
print(np.average(w8, weights = w8))

# standard deviation
u = np.mean(w8)
mystd = np.sqrt(np.mean(abs(w8-u)**2))
print(mystd)

# inbuilt function for standard deviation 
dev = np.std(w8)
print(dev)

# variance
print(dev**2)
print(np.var(w8))

3.0
1.118033988749895
1.118033988749895
1.2500000000000002
1.25
